const app = document.querySelector('#app');
const nav = document.querySelector('#site-nav');
const navToggle = document.querySelector('.nav-toggle');
let courses = [];
let resources = {};

const icons = { search: '<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5"/></svg>', chevron: '<span class="chevron" aria-hidden="true">⌄</span>' };
const safe = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const allTopics = () => courses.flatMap((course) => course.sections.flatMap((section) => section.topics.map((topic) => ({ topic, course, section }))));
const storage = { get(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }, set(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); } catch {} } };
const doneTopics = () => storage.get('mpt-done', {});
const topicKey = (courseId, code) => `${courseId}:${code}`;
const countTopics = (course) => course.sections.reduce((sum, section) => sum + section.topics.length, 0);
const countDone = (course) => course.sections.reduce((sum, section) => sum + section.topics.filter((topic) => doneTopics()[topicKey(course.id, topic.code)]).length, 0);
const percent = (course) => Math.round((countDone(course) / countTopics(course)) * 100);

function searchBox(value = '', placeholder = 'Search topics and subtopics') { return `<label class="search-box" aria-label="${placeholder}">${icons.search}<input class="search-input" type="search" value="${safe(value)}" placeholder="${placeholder}"><span class="shortcut">/</span></label>`; }
function courseCard(course) { return `<a class="course-card ${course.accent}" href="#/course/${course.id}"><div class="card-top"><span class="course-code">${safe(course.code)}</span><span class="arrow" aria-hidden="true">↗</span></div><h3>${safe(course.title)}</h3><p>${safe(course.description)}</p><div class="course-stats"><span><strong>${course.sections.length}</strong>sections</span><span><strong>${countTopics(course)}</strong>topics</span><span><strong>${percent(course)}%</strong>complete</span></div><div class="progress-wrap"><div class="progress-meta"><span>Progress</span><span>${countDone(course)} of ${countTopics(course)} done</span></div><div class="progress"><i style="width:${percent(course)}%"></i></div></div></a>`; }
function home() { return `<section class="hero"><div class="eyebrow">Master of Physiotherapy</div><h1>MPT Study Portal</h1><p class="lede">Your quick route from course outline to the notes you need before the next exam.</p><div class="hero-sub"><span class="hero-rule"></span><span>Two courses · one focused workspace</span></div></section><section><div class="section-label"><h2>Your courses</h2><p>Pick up where you left off</p></div><div class="course-grid">${courses.map(courseCard).join('')}</div></section><section class="home-lower"><div><div class="eyebrow">Keep moving</div><h2>Useful, close at hand.</h2><div class="quick-links"><a class="quick-link" href="#/qbank">Question bank <span>↗</span></a><a class="quick-link" href="#/resources">Books & resources <span>↗</span></a></div></div><div class="search-block"><div class="eyebrow">Search everything</div><h2>Find a topic in seconds.</h2>${searchBox('', 'Search all topics and subtopics')}</div></section>`; }
function topicMatches(topic, query) { const haystack = [topic.code, topic.title, ...topic.subtopics].join(' ').toLowerCase(); return haystack.includes(query.toLowerCase()); }
function renderTopic(course, topic, query = '') { const done = !!doneTopics()[topicKey(course.id, topic.code)]; const visibleSubtopics = topic.subtopics.filter((subtopic) => !topic.focusSubtopics || topic.focusSubtopics.includes(subtopic)); const chips = visibleSubtopics.slice(0, 7).map((subtopic) => `<span class="chip">${safe(subtopic)}${topic.focusSubtopics?.includes(subtopic) ? ' ·' : ''}</span>`).join(''); return `<article class="topic ${done ? 'is-done' : ''}" data-topic="${safe(topic.code)}"><div class="topic-main"><div class="topic-titleline"><span class="topic-code">${safe(topic.code)}</span>${topic.focus ? '<span class="listed-badge">Listed</span>' : ''}<h3>${safe(topic.title)}</h3></div>${chips ? `<div class="chips">${chips}</div>` : ''}${topic.subtopics.length > 7 ? `<p class="topic-note">+ ${topic.subtopics.length - 7} more subtopics</p>` : ''}${topic.note ? `<p class="topic-note">${safe(topic.note)}</p>` : ''}</div><div class="topic-actions">${topic.pdf ? `<a class="pdf-button" href="${safe(topic.pdf)}" target="_blank" rel="noreferrer">Notes PDF ↗</a>` : '<span class="pdf-button disabled" aria-disabled="true">PDF coming soon</span>'}<label class="done-label"><input class="done-checkbox" type="checkbox" data-course="${course.id}" data-topic="${safe(topic.code)}" ${done ? 'checked' : ''}> Done</label></div></article>`; }
function coursePage(course, sectionIndex = 0) { const currentDone = countDone(course); return `<div class="page-head"><div><div class="eyebrow">${safe(course.code)}</div><h1>${safe(course.title)}</h1><p class="lede">${safe(course.description)}</p></div><div class="head-progress"><strong>${Math.round((currentDone / countTopics(course)) * 100)}%</strong><span>${currentDone} of ${countTopics(course)} topics complete</span><div class="progress"><i style="width:${percent(course)}%"></i></div></div></div><div class="course-controls">${searchBox('', 'Search this course')}<label class="toggle"><input id="focus-toggle" type="checkbox"><span>Focus topics only</span></label></div><div id="course-sections">${course.sections.map((section, index) => `<details class="accordion" ${index === sectionIndex ? 'open' : ''} data-section="${index}"><summary><span class="section-number">0${index + 1}</span><h2>${safe(section.title)}</h2>${icons.chevron}</summary><div class="topic-list">${section.topics.map((topic) => renderTopic(course, topic)).join('')}</div></details>`).join('')}</div><div class="section-nav">${sectionIndex > 0 ? `<a class="text-button" href="#/course/${course.id}?section=${sectionIndex - 1}">← Previous section</a>` : '<span class="text-button muted">Previous section</span>'}${sectionIndex < course.sections.length - 1 ? `<a class="text-button" href="#/course/${course.id}?section=${sectionIndex + 1}">Next section →</a>` : '<span class="text-button muted">Next section</span>'}</div>`; }
function qbank() { return `<section class="content-intro"><div class="eyebrow">Practice under pressure</div><h1>Question bank</h1><p class="lede">A place for past papers, viva prompts and topic-wise revision questions. Entries are ready to add as they become available.</p></section><div class="qbank-list">${courses.map((course) => `<section class="qbank-course"><div class="eyebrow">${safe(course.code)}</div><h2>${safe(course.title)}</h2>${course.sections.flatMap((section) => section.topics.slice(0, 3).map((topic) => `<div class="qbank-topic"><strong>${safe(topic.code)}</strong><span>${safe(topic.title)}</span><small class="placeholder">Questions to be added later</small></div>`)).join('')}</section>`).join('')}</div>`; }
function resourcesPage() { return `<section class="content-intro"><div class="eyebrow">Read deeper</div><h1>Resources</h1><p class="lede">Recommended books and reference material, grouped by course so your reading list stays practical.</p></section><div class="resources-layout"><aside class="resource-nav"><div class="eyebrow">On this page</div>${courses.map((course) => `<p>${safe(course.code)}</p>`).join('')}</aside><div>${courses.map((course) => { const resource = resources[course.id] || { books: [] }; return `<section class="resource-course"><div class="eyebrow">${safe(course.code)}</div><h2>${safe(resource.label || course.title)}</h2>${resource.books?.length ? resource.books.map((book, index) => `<div class="book"><span class="book-index">0${index + 1}</span><div><p>${safe(book.title)}</p><small>${safe(book.publisher)}</small></div></div>`).join('') : '<p class="empty-state">Resource links will be added later.</p>'}</section>`; }).join('')}</div></div>`; }

function route() { const [path, queryString = ''] = location.hash.replace(/^#\/?/, '').split('?'); const params = new URLSearchParams(queryString); let page = ''; if (!path) page = home(); else if (path === 'qbank') page = qbank(); else if (path === 'resources') page = resourcesPage(); else if (path.startsWith('course/')) { const course = courses.find((item) => item.id === path.split('/')[1]); page = course ? coursePage(course, Number(params.get('section')) || 0) : home(); } else page = home(); app.innerHTML = page; app.focus({ preventScroll: true }); bindPage(); document.querySelectorAll('.site-nav a').forEach((link) => link.setAttribute('aria-current', link.getAttribute('href') === `#/${path ? path.split('?')[0] : ''}` ? 'page' : 'false')); }
function bindPage() { document.querySelectorAll('.search-input').forEach((input) => input.addEventListener('input', () => { const query = input.value.trim(); if (location.hash.includes('/course/')) { document.querySelectorAll('.topic').forEach((row) => { const topic = allTopics().find((item) => item.topic.code === row.dataset.topic)?.topic; row.hidden = !!query && (!topic || !topicMatches(topic, query)); }); } else if (query) showSearchResults(query); })); document.querySelectorAll('.done-checkbox').forEach((checkbox) => checkbox.addEventListener('change', () => { const done = doneTopics(); done[topicKey(checkbox.dataset.course, checkbox.dataset.topic)] = checkbox.checked; storage.set('mpt-done', done); route(); })); document.querySelector('#focus-toggle')?.addEventListener('change', (event) => document.querySelectorAll('.topic').forEach((row) => { const topic = allTopics().find((item) => item.topic.code === row.dataset.topic)?.topic; row.hidden = event.target.checked && !topic?.focus; })); }
function showSearchResults(query) { const results = allTopics().filter(({ topic }) => topicMatches(topic, query)); const block = document.querySelector('.search-block'); if (!block) return; block.querySelector('.search-results')?.remove(); const resultsEl = document.createElement('div'); resultsEl.className = 'search-results'; resultsEl.innerHTML = results.length ? results.slice(0, 6).map(({ topic, course }) => `<a class="quick-link" href="#/course/${course.id}"><span>${safe(topic.code)} · ${safe(topic.title)}</span><span>↗</span></a>`).join('') : '<p class="empty-state">No matching topics yet.</p>'; block.append(resultsEl); }
async function init() { try { const [courseResponse, resourceResponse] = await Promise.all([fetch('data/courses.json'), fetch('data/resources.json')]); courses = (await courseResponse.json()).courses; resources = await resourceResponse.json(); route(); } catch (error) { app.innerHTML = '<p class="empty-state">The study data could not be loaded. Open this site through a local static server or GitHub Pages.</p>'; console.error(error); } }
navToggle.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); navToggle.setAttribute('aria-expanded', open); });
document.querySelector('#theme-toggle').addEventListener('click', () => { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; try { localStorage.setItem('mpt-theme', next); } catch {} document.querySelector('.theme-label').textContent = next === 'dark' ? 'Dark' : 'Light'; document.querySelector('#theme-toggle').setAttribute('aria-label', `Switch to ${next === 'dark' ? 'light' : 'dark'} mode`); });
const savedTheme = document.documentElement.dataset.theme || 'light';
document.querySelector('.theme-label').textContent = savedTheme === 'dark' ? 'Dark' : 'Light';
document.querySelector('#theme-toggle').setAttribute('aria-label', `Switch to ${savedTheme === 'dark' ? 'light' : 'dark'} mode`);
window.addEventListener('hashchange', () => { nav.classList.remove('is-open'); route(); });
document.addEventListener('keydown', (event) => { if (event.key === '/' && !['INPUT','TEXTAREA'].includes(document.activeElement.tagName)) { event.preventDefault(); document.querySelector('.search-input')?.focus(); } });
init();
