const app = document.querySelector('#app');
const nav = document.querySelector('#site-nav');
const navToggle = document.querySelector('.nav-toggle');
const footerUpdated = document.querySelector('#footer-updated');
const courseSources = [
  { id: 'mpt101', path: 'pack/data/mpt101.json', accent: 'coral' },
  { id: 'mpt104', path: 'pack/data/mpt104.json', accent: 'teal' }
];
let courses = [];
let hasRendered = false;

const icons = { search: '<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5"/></svg>' };
const safe = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const dateValue = (value) => { const match = String(value || '').match(/(\d{2})-(\d{2})-(\d{4})/); return match ? new Date(`${match[3]}-${match[2]}-${match[1]}`) : new Date(0); };
const formatDate = (value) => { const date = dateValue(value); return date.getTime() ? `${String(date.getDate()).padStart(2, '0')}-${String(date.getMonth() + 1).padStart(2, '0')}-${date.getFullYear()}` : String(value || ''); };
const isSpecified = (value) => value !== undefined && value !== null && value !== '' && !/^not specified/i.test(String(value));
const resourceGroups = [['textbooks', 'Textbooks'], ['references', 'Reference books'], ['eresources', 'E-resources'], ['tools', 'Tools / Software'], ['extra', 'Beyond-syllabus topics']];

function searchBox(placeholder = 'Search topics and sessions') { return `<label class="search-box"><span class="visually-hidden">${safe(placeholder)}</span>${icons.search}<input class="search-input" type="search" placeholder="${safe(placeholder)}" data-planning-search><span class="shortcut">/</span></label>`; }
function courseCard(course) { const hours = String(course.theoryHours || '0').replace(/\s*(hours?|hrs?)(\s*)$/i, ''); return `<a class="course-card ${safe(course.accent)}" href="#/${course.id}/home"><div class="card-top"><span class="course-code">${safe(course.code)} · ${safe(course.shortName)}</span><span class="arrow" aria-hidden="true">↗</span></div><h3>${safe(course.title)}</h3><p>${safe(course.shortName)} course plan and learning material.</p><p class="card-summary">${course.cos.length} COs · ${course.units.length} units · ${safe(hours)} hrs</p></a>`; }
function home() { return `<section class="hero"><div class="eyebrow">Master of Physiotherapy</div><h1>MPT Study Portal</h1><p class="lede">Course plans, outcomes, assessments and learning material in one focused workspace.</p></section><section><div class="section-label"><h2>Your courses</h2><p>Choose a course to begin</p></div><div class="course-grid">${courses.map(courseCard).join('')}</div></section><section class="home-search"><div class="eyebrow">Search everything</div><h2>Find a topic in seconds.</h2>${searchBox('Search all course topics')}</section>`; }
function schemeRows(course) { const fields = [['credits', 'Credits'], ['ltp', 'L-T-P'], ['theoryHours', 'Theory hours'], ['practicalHours', 'Practical hours'], ['theorySessions', 'Theory sessions'], ['labSessions', 'Practical sessions'], ['programme', 'Programme'], ['year', 'Year'], ['academicYear', 'Academic year']]; return fields.filter(([key]) => isSpecified(course[key])).map(([key, label]) => `<div class="scheme-item"><dt>${label}</dt><dd>${safe(course[key])}</dd></div>`).join(''); }
function courseHome(course) { return `<section class="course-intro"><div class="eyebrow">${safe(course.code)} · ${safe(course.shortName)}</div><h1>${safe(course.title)} (${safe(course.code)})</h1><a class="primary-button" href="${safe(course.syllabusPdf.replace(/^assets\//, 'pack/assets/'))}" download>Download Syllabus</a></section><section class="content-section"><h2>Course Outcome</h2><div class="outcome-list">${course.cos.map((co) => `<article class="outcome"><strong>${safe(co.id.replace('CO', 'CO-'))}</strong><p>${safe(co.text)}</p><span class="tag">${safe(co.bloom)}</span></article>`).join('')}</div></section><section class="content-section"><h2>CO-PO Mapping</h2><div class="table-scroll"><table class="mapping-table"><thead><tr><th scope="col">CO</th>${course.pos.map((po) => `<th scope="col">${safe(po.id)}</th>`).join('')}</tr></thead><tbody>${course.copoMap.rows.map((row) => `<tr><th scope="row">${safe(row.co.replace('CO', 'CO-'))}</th>${course.pos.map((po) => { const value = row.values[po.id]; return `<td class="map-${value || 'empty'}">${value || '-'}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div><div class="legend"><span><i class="map-swatch map-3">3</i> Strong</span><span><i class="map-swatch map-2">2</i> Moderate</span><span><i class="map-swatch map-1">1</i> Low</span><span><i class="map-swatch">-</i> No correlation</span></div><div class="po-list">${course.pos.map((po) => `<article><strong>${safe(po.id)} · ${safe(po.title)}</strong><p>${safe(po.text)}</p></article>`).join('')}</div></section><section class="content-section"><h2>Teaching and Examination Scheme</h2><dl class="scheme-grid">${schemeRows(course)}</dl></section><section class="content-section resource-person"><h2>Resource Person</h2><p>${safe(course.faculty)}</p></section>`; }
function planningPage(course) { const units = course.units.map((unit) => `<tr><th scope="row">${safe(unit.unit)}</th><td>${safe(unit.title)}</td><td>${safe(unit.topics)}</td><td>${safe(unit.hours)}</td><td>${safe(unit.marks)}</td><td>${safe(unit.cos)}</td></tr>`).join(''); const faculty = [...new Set(course.lessonPlan.map((item) => item.faculty))].sort(); const unitsList = [...new Set(course.lessonPlan.map((item) => item.unit))].sort(); const cos = [...new Set(course.lessonPlan.flatMap((item) => String(item.co).split(/,\s*/)))].sort(); return `<section class="content-section"><div class="section-heading"><div><div class="eyebrow">Course planning</div><h1>Units and lesson plan</h1></div></div><div class="table-scroll"><table class="unit-table"><thead><tr><th>Unit</th><th>Title</th><th>Key topics</th><th>Hours</th><th>Marks</th><th>COs</th></tr></thead><tbody>${units}</tbody></table></div></section><section class="content-section lesson-section"><div class="section-heading"><div><h2>Session-wise lesson plan</h2><p class="muted">Filter the plan by unit, faculty, outcome or session type.</p></div><strong class="hours-summary" id="hours-summary"></strong></div><div class="planning-filters"><select data-filter="unit" aria-label="Filter by unit"><option value="">All units</option>${unitsList.map((value) => `<option>${safe(value)}</option>`).join('')}</select><select data-filter="faculty" aria-label="Filter by faculty"><option value="">All faculty</option>${faculty.map((value) => `<option>${safe(value)}</option>`).join('')}</select><select data-filter="co" aria-label="Filter by CO"><option value="">All COs</option>${cos.map((value) => `<option>${safe(value)}</option>`).join('')}</select><select data-filter="type" aria-label="Filter by type"><option value="">Theory and practical</option><option>Theory</option><option>Practical</option></select>${searchBox('Search lesson plan')}</div><div class="table-scroll lesson-scroll"><table class="lesson-table"><thead><tr><th>Session</th><th>Unit</th><th>Topic</th><th>Faculty</th><th>Hours</th><th>CO</th><th>Method</th><th>Assessment</th><th>Planned date</th><th>Remarks</th></tr></thead><tbody id="lesson-rows"></tbody></table></div></section>`; }
function lessonRows(course) { return course.lessonPlan.map((item) => `<tr data-unit="${safe(item.unit)}" data-faculty="${safe(item.faculty)}" data-co="${safe(item.co)}" data-type="${safe(item.type)}" data-search="${safe([item.topic, item.slo, item.resource, item.method, item.assessment, item.remarks].join(' '))}"><td data-label="Session">${safe(item.session)}</td><td data-label="Unit">${safe(item.unit)}</td><td data-label="Topic"><details><summary>${safe(item.topic)}</summary><p><strong>Learning outcome:</strong> ${safe(item.slo)}</p><p><strong>Resource:</strong> ${safe(item.resource)}</p></details></td><td data-label="Faculty">${safe(item.faculty)}</td><td data-label="Hours">${safe(item.hours)}</td><td data-label="CO">${safe(item.co)}</td><td data-label="Method">${safe(item.method)}</td><td data-label="Assessment">${safe(item.assessment)}</td><td data-label="Planned date">${safe(item.plannedDate)}</td><td data-label="Remarks">${safe(item.remarks)}</td></tr>`).join(''); }
function assessmentPage(course) { const items = course.evaluation.filter((item) => item.component !== 'Total'); const total = course.evaluation.find((item) => item.component === 'Total'); return `<section class="content-section"><div class="eyebrow">Assessment</div><h1>Evaluation scheme</h1><div class="table-scroll"><table class="assessment-table"><thead><tr><th>Component</th><th>Description</th><th>Weightage</th><th>COs assessed</th><th>Schedule</th></tr></thead><tbody>${items.map((item) => `<tr><th scope="row">${safe(item.component)}</th><td>${safe(item.description)}</td><td><div class="weightage"><span>${safe(item.weightage)}%</span><i style="width:${Number(item.weightage) || 0}%"></i></div></td><td>${safe(item.cos)}</td><td>${safe(item.schedule)}</td></tr>`).join('')}</tbody><tfoot><tr><th>Total</th><td></td><th>${safe(total?.weightage || 0)}%</th><td></td><td></td></tr></tfoot></table></div></section>`; }
function resourceItem(item) { return `<article class="resource-item"><strong>${safe(item.title || item.purpose || item.topic || item.item)}</strong><p>${safe(item.authors || item.link || item.rationale || item.purpose || '')}</p><small>${safe(item.publisher || item.notes || item.delivery || item.access || '')}</small></article>`; }
function materialPage(course) { return `<section class="content-section"><h1>Learning Resources</h1><div class="resource-groups">${resourceGroups.map(([key, label]) => `<section><h3>${label}</h3>${(course.resources?.[key] || []).length ? course.resources[key].map(resourceItem).join('') : '<p class="muted">No resources listed.</p>'}</section>`).join('')}</div></section>`; }

function updateNav(course, page) { const links = course ? `<a href="#/" class="all-courses">← All courses</a><span class="nav-course">${safe(course.shortName)}</span><span class="nav-divider">|</span><a href="#/${course.id}/home" aria-current="${page === 'home' ? 'page' : 'false'}">Home</a><a href="#/${course.id}/planning" aria-current="${page === 'planning' ? 'page' : 'false'}">Course Planning</a><a href="#/${course.id}/assessment" aria-current="${page === 'assessment' ? 'page' : 'false'}">Assessment</a><a href="#/${course.id}/material" aria-current="${page === 'material' ? 'page' : 'false'}">Material</a>` : '<a href="#/" aria-current="page">Home</a>'; nav.innerHTML = `${links}<button id="theme-toggle" class="theme-toggle" type="button" aria-label="Switch theme" title="Switch theme"><span class="theme-icon">☼</span><span class="theme-label"></span></button>`; const theme = document.documentElement.dataset.theme || 'light'; nav.querySelector('.theme-label').textContent = theme === 'dark' ? 'Dark' : 'Light'; nav.querySelector('#theme-toggle').setAttribute('aria-label', `Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`); nav.querySelector('#theme-toggle').addEventListener('click', toggleTheme); }
function toggleTheme() { const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'; document.documentElement.dataset.theme = next; try { localStorage.setItem('mpt-theme', next); } catch {} updateNav(currentCourse(), currentPage()); }
function currentCourse() { const id = location.hash.replace(/^#\/?/, '').split('/')[0]; return courses.find((course) => course.id === id); }
function route() { const parts = location.hash.replace(/^#\/?/, '').split('/').filter(Boolean); const course = courses.find((item) => item.id === parts[0]); const page = parts[1] || 'home'; let markup = home(); if (course) { markup = page === 'planning' ? planningPage(course) : page === 'assessment' ? assessmentPage(course) : page === 'material' ? materialPage(course) : courseHome(course); } app.innerHTML = markup; updateNav(course, course ? page : ''); footerUpdated.textContent = `Updated on : ${formatDate((courses.slice().sort((a, b) => dateValue(b.lastUpdated) - dateValue(a.lastUpdated))[0] || {}).lastUpdated)}`; if (hasRendered) { app.focus({ preventScroll: true }); } hasRendered = true; bindPage(course, page); }
function applyLessonFilters() { const section = document.querySelector('.lesson-section'); if (!section) return; const values = Object.fromEntries([...section.querySelectorAll('[data-filter]')].map((select) => [select.dataset.filter, select.value])); const query = section.querySelector('[data-planning-search]')?.value.toLowerCase() || ''; let total = 0; section.querySelectorAll('#lesson-rows tr').forEach((row) => { const matches = (!values.unit || row.dataset.unit === values.unit) && (!values.faculty || row.dataset.faculty === values.faculty) && (!values.co || row.dataset.co.includes(values.co)) && (!values.type || row.dataset.type === values.type) && (!query || row.dataset.search.toLowerCase().includes(query)); row.hidden = !matches; if (matches) total += Number(row.querySelector('[data-label="Hours"]')?.textContent) || 0; }); section.querySelector('#hours-summary').textContent = `Total hours: ${total}`; }
function bindPage(course, page) { document.querySelectorAll('[data-filter], [data-planning-search]').forEach((control) => control.addEventListener('input', applyLessonFilters)); const homeSearch = document.querySelector('.home-search .search-input'); homeSearch?.addEventListener('input', () => { const query = homeSearch.value.trim().toLowerCase(); homeSearch.closest('.home-search').querySelector('.global-results')?.remove(); if (!query) return; const matches = courses.flatMap((item) => item.lessonPlan.filter((lesson) => lesson.topic.toLowerCase().includes(query)).slice(0, 4).map((lesson) => ({ course: item, lesson }))); const result = document.createElement('div'); result.className = 'global-results'; result.innerHTML = matches.length ? matches.map(({ course: item, lesson }) => `<a href="#/${item.id}/planning"><span>${safe(item.code)} · ${safe(lesson.topic)}</span><span>↗</span></a>`).join('') : '<p class="muted">No matching topics yet.</p>'; homeSearch.closest('.home-search').append(result); }); if (page === 'planning') { const rows = document.querySelector('#lesson-rows'); rows.innerHTML = lessonRows(course); applyLessonFilters(); } }
async function init() { try { courses = await Promise.all(courseSources.map(async (source) => ({ ...source, ...await (await fetch(source.path)).json() }))); route(); } catch (error) { app.innerHTML = '<p class="empty-state">The study data could not be loaded. Open this site through a local static server or GitHub Pages.</p>'; console.error(error); } }
navToggle.addEventListener('click', () => { const open = nav.classList.toggle('is-open'); navToggle.setAttribute('aria-expanded', String(open)); });
window.addEventListener('hashchange', () => { nav.classList.remove('is-open'); route(); });
document.addEventListener('keydown', (event) => { if (event.key === '/' && !['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement.tagName)) { event.preventDefault(); document.querySelector('.search-input')?.focus(); } });
init();